"""The ActionScript and BES XML highlighting grammars (issue #116).

Generated by ``tools/generate_tmlanguage.py`` from a committed verb list
(``tools/data/actionscript_verbs.txt``) and the extractor's own tables. These
tests read the grammars' regexes with Python's ``re``, which is close to, but
not, the Oniguruma engine VS Code runs: they catch logic errors (which words a
rule takes, where it stops), not engine quirks. Each TextMate ``(?:^|\\G)``
anchor is read as ``^``.

The rule that matters most in a ``.bes`` file: no ActionScript rule runs past
a ``]]>`` or ``</ActionScript>``, so a broken body can never color the rest of
the file. Every single-line rule is checked against that below.
"""

from __future__ import annotations

import functools
import json
import os
import re
from pathlib import Path
from typing import Any

import pytest
from _helpers import load_tool

from bigfix_relevance_analyzer.extract import (
    _ACTIONSCRIPT_MIMETYPES,
    _HEREDOC_RE,
    _RELEVANT_TAGS,
    _iter_substitution_spans,
)

REPO_ROOT = Path(__file__).resolve().parent.parent
GENERATOR = REPO_ROOT / "tools" / "generate_tmlanguage.py"
KEYWORD_GENERATOR = REPO_ROOT / "tools" / "generate_actionscript_keywords.py"
VERBS = REPO_ROOT / "tools" / "data" / "actionscript_verbs.txt"

HOST_END = "]]></ActionScript>"


@functools.cache
def _generator() -> Any:
    return load_tool(GENERATOR, "_generate_tmlanguage")


def _verbs() -> list[str]:
    return [
        line for line in VERBS.read_text("utf-8").splitlines() if line and not line.startswith("#")
    ]


def _python(pattern: str) -> re.Pattern[str]:
    r"""A grammar regex for Python's `re`: `\G` only ever appears as `(?:^|\G)`."""
    assert pattern.count(r"\G") == pattern.count(r"(?:^|\G)"), pattern
    return re.compile(pattern.replace(r"(?:^|\G)", "^"))


@functools.cache
def _grammar() -> dict[str, Any]:
    grammar: dict[str, Any] = _generator().actionscript_grammar()
    return grammar


def _repository() -> dict[str, Any]:
    repository: dict[str, Any] = _grammar()["repository"]
    return repository


@functools.cache
def _rule(name: str) -> re.Pattern[str]:
    return _python(_repository()[name]["match"])


def _scan(line: str, names: list[str] | None = None) -> list[tuple[str, str]]:
    """``(rule, text)`` for each single-line rule match on ``line``, the way
    TextMate picks them: the earliest match wins, ties go to the rule listed
    first, and scanning resumes where the match ended."""
    grammar = _grammar()
    repository = grammar["repository"]
    if names is None:
        names = [include["include"].removeprefix("#") for include in grammar["patterns"]]
    rules = [(name, _rule(name)) for name in names if "match" in repository[name]]
    found: list[tuple[str, str]] = []
    position = 0
    while position < len(line):
        best: tuple[int, int, str, re.Match[str]] | None = None
        for order, (name, rule) in enumerate(rules):
            match = rule.search(line, position)
            if match is None or match.end() == match.start():
                continue
            key = (match.start(), order)
            if best is None or key < (best[0], best[1]):
                best = (match.start(), order, name, match)
        if best is None:
            break
        found.append((best[2], best[3].group()))
        position = best[3].end()
    return found


# ---------------------------------------------------------------------------
# Step 1: the verb list and where it comes from
# ---------------------------------------------------------------------------


def test_the_verb_file_is_sorted_lowercase_single_spaced_and_nonempty() -> None:
    verbs = _verbs()
    assert len(verbs) > 300
    assert verbs == sorted(set(verbs))
    for verb in verbs:
        assert verb == verb.lower(), verb
        assert verb == " ".join(verb.split()), verb


def test_the_verb_file_holds_the_verbs_the_highlighting_depends_on() -> None:
    """The override's `surrender device id` and the structural verbs the
    grammar treats specially."""
    verbs = set(_verbs())
    for verb in (
        "surrender device id",
        "download now as",
        "createfile until",
        "appendfile",
        "override run",
        "override wait",
        "if",
        "elseif",
        "else",
        "endif",
        "continue if",
        "pause while",
    ):
        assert verb in verbs, verb


def test_the_verb_file_names_its_source() -> None:
    header = [line for line in VERBS.read_text("utf-8").splitlines() if line.startswith("#")]
    text = "\n".join(header)
    assert "generate_actionscript_keywords.py" in text
    for name in ("ExpandedActionScript.schclass", "bigfix_overrides.schclass"):
        assert re.search(rf"{re.escape(name)} sha256 [0-9a-f]{{64}}", text), name


def test_the_filtered_keyword_module_is_a_subset_of_the_full_verb_list() -> None:
    """The 37-word relevance guard is drawn from the same 323 verbs."""
    from bigfix_relevance_analyzer._actionscript_keywords import ACTIONSCRIPT_KEYWORDS

    assert set(_verbs()) >= ACTIONSCRIPT_KEYWORDS


def _schclass_dir() -> Path | None:
    configured = os.environ.get("PRE_COMMIT_BIGFIX_SCHCLASS_DIR")
    candidate = (
        Path(configured)
        if configured
        else REPO_ROOT.parent / "pre-commit-bigfix" / "pre_commit_bigfix" / "schclass_data"
    )
    return candidate if (candidate / "ExpandedActionScript.schclass").is_file() else None


def test_the_full_verb_list_matches_the_vendored_schclass() -> None:
    """Skipped without a pre-commit-bigfix checkout: beside this one, or named
    by PRE_COMMIT_BIGFIX_SCHCLASS_DIR."""
    schclass_dir = _schclass_dir()
    if schclass_dir is None:
        pytest.skip("no pre-commit-bigfix schclass_data to compare against")
    tool = load_tool(KEYWORD_GENERATOR, "_generate_actionscript_keywords")
    assert tool.render_verbs(schclass_dir) == VERBS.read_text("utf-8")
    assert tool.main(["--schclass-dir", str(schclass_dir), "--check"]) == 0


# ---------------------------------------------------------------------------
# Step 3: the ActionScript rules, one regex at a time
# ---------------------------------------------------------------------------

CONTROL = {"if", "elseif", "else", "endif", "continue if", "pause while"}


def _verb_match(line: str) -> tuple[str, str] | None:
    """The verb rule that takes ``line``'s first word(s), and what it took."""
    for name in ("control", "command"):
        match = _rule(name).match(line)
        if match:
            return name, match.group(1)
    return None


@pytest.mark.parametrize("case", ["lower", "upper", "title"])
def test_every_verb_is_colored_at_line_start_in_any_case(case: str) -> None:
    for verb in _verbs():
        if verb in {"createfile until", "appendfile", "override run", "override wait"}:
            continue  # rules of their own, below
        written = getattr(verb, case)()
        for line in (written, f"  {written} x", f"\t{written}"):
            found = _verb_match(line)
            assert found is not None, line
            rule, taken = found
            assert " ".join(taken.lower().split()) == verb, (line, taken)
            assert rule == ("control" if verb in CONTROL else "command"), line


def test_a_multi_word_verb_wins_over_its_first_word() -> None:
    assert _verb_match("action log command x") == ("command", "action log command")
    assert _verb_match("download now as x.exe http://x") == ("command", "download now as")
    assert _verb_match("setting delete x") == ("command", "setting delete")


def test_extra_spaces_between_a_verbs_words_still_match() -> None:
    found = _verb_match("download  now   as x")
    assert found is not None and " ".join(found[1].split()) == "download now as"


def test_a_verb_is_never_a_prefix_of_a_longer_word() -> None:
    """The defect in bigfix/highlight-bigfix-actionscript: `runner` colored `run`."""
    assert _verb_match("runner x") is None
    assert _verb_match("ifx") is None
    assert _verb_match("runhidden x") == ("command", "runhidden")


def test_a_verb_is_matched_only_at_line_start() -> None:
    for line in ("x run y", "// run y", '"run" y', "{run} y"):
        assert _verb_match(line) is None, line


def test_a_condition_written_against_its_keyword_still_colors_the_keyword() -> None:
    """`if{...}`, `continue if{...}`: real content writes both spacings."""
    assert _verb_match("if{exists file 'x'}") == ("control", "if")
    assert _verb_match("continue if{x}") == ("control", "continue if")


def test_a_verb_right_before_the_end_of_the_body_still_colors() -> None:
    assert _verb_match("endif]]></ActionScript>") == ("control", "endif")
    assert _verb_match("endif</ActionScript>") == ("control", "endif")


def test_a_comment_is_a_whole_line_from_its_start() -> None:
    comment = _rule("comment")
    assert comment.match("// x") and comment.match("   // x") and comment.match("//")
    assert not comment.search("download http://x")
    assert not comment.match("run x // y")
    assert comment.match("// done]]></ActionScript>").group() == "// done"  # type: ignore[union-attr]


SUBSTITUTION_LINES = [
    'wait "{pathname of file "x"}" /s',
    'if {exists file "a}b"}',
    "x {{literal} {name of operating system}",
    "x {value }} braced} y",
    "{a}{b} {{ template }} {c}",
    'parameter "p"="{(it as string) of 1}"',
    "x {unterminated",
    "x {}",
    'x {"unterminated string}',
    "x { spaced } y",
]


@pytest.mark.parametrize("line", SUBSTITUTION_LINES)
def test_substitutions_are_exactly_the_ones_the_extractor_reads(line: str) -> None:
    """The colored `{...}` bodies, in order, are the extractor's sites."""
    read = [text for _line, _offset, text, _cond in _iter_substitution_spans(line)]
    found = []
    for rule, text in _scan(line):
        if rule == "substitution":
            found.append(text)
        elif rule == "string":
            inside = _scan(text, ["substitution-escape", "substitution"])
            found.extend(token for name, token in inside if name == "substitution")
    contents = [_rule("substitution").match(text).group(2).strip() for text in found]  # type: ignore[union-attr]
    assert [text for text in contents if text] == read


def test_a_doubled_brace_never_opens_a_substitution() -> None:
    assert [rule for rule, _ in _scan("{{ template }}")] == ["substitution-escape"]
    assert _scan("{{x}") == [("substitution-escape", "{{")]


def test_a_doubled_close_brace_inside_a_substitution_does_not_close_it() -> None:
    assert _scan("{a }} b}") == [("substitution", "{a }} b}")]


def test_a_string_has_no_escape_character() -> None:
    """`"C:\\Bes\\"` is closed at its second quote (pre-commit-bigfix#16)."""
    assert _scan('run "C:\\Bes\\" /x', ["string"]) == [("string", '"C:\\Bes\\"')]


def test_a_substitution_inside_a_string_may_hold_quotes() -> None:
    line = 'run "{pathname of file "x"}" /s'
    assert _scan(line, ["string"]) == [("string", '"{pathname of file "x"}"')]


def test_an_unterminated_string_ends_at_the_line_or_the_body() -> None:
    assert _scan('run "open', ["string"]) == [("string", '"open')]
    assert _scan(f'run "open{HOST_END}', ["string"]) == [("string", '"open')]


def test_a_url_ends_where_the_console_ends_it() -> None:
    url = _rule("url")
    for line, expected in (
        ("download http://x/y.exe", "http://x/y.exe"),
        ("download https://x/y.exe sha1:1", "https://x/y.exe"),
        ('prefetch x "https://a/b"', "https://a/b"),
        ("x {https://a/b}", "https://a/b"),
        ("x http://a*b", "http://a"),
        (f"x http://a{HOST_END}", "http://a"),
    ):
        match = url.search(line)
        assert match is not None and match.group() == expected, line


@pytest.mark.parametrize(
    "line",
    [
        "createfile until END",
        "  CreateFile   Until   __EOF__  ",
        "appendfile until X",
        "createfile until",
        "createfile until a b",
        "createfile untilX Y",
        "createfiles until X",
    ],
)
def test_a_heredoc_opens_exactly_where_the_extractor_opens_one(line: str) -> None:
    begin = _python(_repository()["heredoc"]["begin"]).match(line)
    expected = _HEREDOC_RE.match(line)
    assert (begin is None) == (expected is None), line
    if begin and expected:
        assert begin.group(2) == expected.group(1)


def _heredoc_end(marker: str) -> re.Pattern[str]:
    """The end rule with its backreference resolved, as the engine does it."""
    end = _repository()["heredoc"]["end"]
    return _python(end.replace(r"\2", re.escape(marker)))


def test_a_heredoc_marker_stops_at_the_end_of_the_body() -> None:
    """`createfile until END]]>`: the marker is `END`, as the extractor reads
    the decoded body, and the heredoc may open at all only because the body's
    end counts as the end of the line (PR #119 review)."""
    begin = _python(_repository()["heredoc"]["begin"])
    for line in (
        "createfile until END]]>",
        "createfile until END</ActionScript>",
        "createfile until END ]]>",
    ):
        found = begin.match(line)
        assert found is not None and found.group(2) == "END", line


def test_a_heredoc_ends_only_on_its_bare_marker_line() -> None:
    end = _heredoc_end("END.x")
    assert end.search("END.x") and end.search("  END.x  ")
    assert not end.search("END.x more") and not end.search("ENDax") and not end.search("x END.x")


def test_a_heredoc_left_open_ends_with_the_body() -> None:
    end = _heredoc_end("END")
    for line in ("]]></ActionScript>", "text]]>", "</ActionScript>"):
        assert end.search(line), line


def test_a_heredoc_body_is_raw_text_with_substitutions() -> None:
    patterns = _repository()["heredoc"]["patterns"]
    assert patterns == [{"include": "#substitution-escape"}, {"include": "#substitution"}]


def test_appendfile_text_is_raw_with_substitutions() -> None:
    rule = _repository()["appendfile"]
    match = _python(rule["match"]).match("appendfile run {name of it} // x")
    assert match is not None
    assert match.group(1) == "appendfile"
    assert match.group(2) == " run {name of it} // x"
    assert rule["captures"]["2"]["patterns"] == [
        {"include": "#substitution-escape"},
        {"include": "#substitution"},
    ]
    assert _python(rule["match"]).match(f"appendfile x{HOST_END}").group(2) == " x"  # type: ignore[union-attr]


def test_an_override_block_holds_only_option_lines() -> None:
    rule = _repository()["override"]
    begin, end = _python(rule["begin"]), _python(rule["end"])
    assert begin.match("override wait") and begin.match("Override Run")
    for line in ("hidden=true", "  completion = job", "RunAs=currentuser", "timeout_seconds={x}"):
        assert not end.match(line), line
    for line in ("wait cmd.exe", "run x=y", "]]></ActionScript>", "hidden"):
        assert end.match(line), line
    # Blank and comment lines pass through, as pre-commit-bigfix's lint reads
    # the block (bes_actionscript_lint_schclass.py): only a command closes it.
    for line in ("", "   ", "// note", "  //"):
        assert not end.match(line), repr(line)
    assert {"include": "#comment"} in rule["patterns"]
    # Zero-width, so the line that ends the block is still read as a command.
    assert end.match("wait cmd.exe").group() == ""  # type: ignore[union-attr]
    found = end.search("hidden=true]]>")
    assert found is not None and found.start() == len("hidden=true")


SINGLE_LINE_RULES = [
    ("comment", "// note"),
    ("appendfile", "appendfile x"),
    ("string", 'run "open'),
    ("url", "download http://x"),
    ("substitution", "x {unclosed"),
]


@pytest.mark.parametrize(("name", "start"), SINGLE_LINE_RULES)
def test_no_rule_runs_past_the_end_of_the_body(name: str, start: str) -> None:
    """In a `.bes`, the body's `]]>` / `</ActionScript>` must stay for the
    BES grammar to close the element, or the rest of the file is miscolored."""
    for end in ("]]>", "</ActionScript>", "]]></ActionScript>"):
        line = start + end
        for _rule_name, text in _scan(line):
            assert end not in text, (name, line, text)


def test_every_rule_is_single_line_except_the_two_blocks() -> None:
    """Only `heredoc` (begin/end) and `override` (begin/while) span lines;
    each is checked above to stop at the end of the body."""
    multi = {name for name, rule in _repository().items() if "begin" in rule}
    assert multi == {"heredoc", "override", "relevance-dependency"}
    never = _repository()["relevance-dependency"]
    assert never["begin"] == never["end"] == "(?!)"


def test_the_relevance_inside_a_substitution_is_the_relevance_grammar() -> None:
    rule = _repository()["substitution"]
    content = rule["captures"]["2"]
    assert content["name"] == "meta.embedded.line.bigfix-relevance"
    assert content["patterns"] == [{"include": "source.bigfix-relevance"}]


def test_the_actionscript_grammar_references_only_the_relevance_grammar() -> None:
    """Standalone, so it can move to its own extension later (see #116)."""
    text = repr(_generator().actionscript_grammar())
    external = set(re.findall(r"'include': '([a-z][^#']*)'", text))
    assert external == {"source.bigfix-relevance"}


# ---------------------------------------------------------------------------
# Step 3: the BES grammar's element rules
# ---------------------------------------------------------------------------


def _bes_repository() -> dict[str, Any]:
    repository: dict[str, Any] = _generator().bes_grammar()["repository"]
    return repository


def _bes_begin(name: str) -> re.Pattern[str]:
    return _python(_bes_repository()[name]["begin"])


def _actionscript_kind(tag: str) -> str:
    """What the two-stage `<ActionScript>` element makes of a start tag:
    ``actionscript``, ``xml`` (another MIME type), ``empty`` (self-closing)
    or ``none`` (not the element at all). The tag may span lines: each stage
    is a rule of its own, so only the name has to be on the first line."""
    opened = _bes_begin("actionscript").match(tag)
    if opened is None:
        return "none"
    rest = tag[opened.end() :]
    if _bes_begin("actionscript-other-language").search(rest):
        return "xml"
    if rest.rstrip().endswith("/>"):
        return "empty"
    return "actionscript"


@pytest.mark.parametrize(
    ("tag", "expected"),
    [
        ("<ActionScript>", "actionscript"),
        ('<ActionScript MIMEType="application/x-Fixlet-Windows-Shell">', "actionscript"),
        ("<ActionScript MIMEType='application/x-fixlet-windows-shell'>", "actionscript"),
        ('<ActionScript ID="1" MIMEType="APPLICATION/X-FIXLET-WINDOWS-SHELL" >', "actionscript"),
        ('<ActionScript\n\tMIMEType="application/x-Fixlet-Windows-Shell">', "actionscript"),
        ('<ActionScript Comment="a > b">', "actionscript"),
        ('<ActionScript MIMEType="application/x-sh">', "xml"),
        ('<ActionScript\n  MIMEType="application/x-sh">', "xml"),
        ('<ActionScript MIMEType="application/x-Fixlet-Windows-PowerShell">', "xml"),
        ('<ActionScript MIMEType="application/x-AppleScript">', "xml"),
        ('<ActionScript MIMEType="text/x-uri">', "xml"),
        ("<ActionScript/>", "empty"),
        ("<ActionScript\n/>", "empty"),
        ("<ActionScriptX>", "none"),
    ],
)
def test_only_windows_shell_actionscript_is_actionscript(tag: str, expected: str) -> None:
    assert _actionscript_kind(tag) == expected


def test_the_mimetypes_come_from_the_extractor() -> None:
    for mimetype in _ACTIONSCRIPT_MIMETYPES:
        for written in (mimetype, mimetype.upper(), mimetype.title()):
            assert _actionscript_kind(f'<ActionScript MIMEType="{written}">') == "actionscript"


def test_an_actionscript_start_tag_may_span_lines() -> None:
    """641 of 7,759 Windows-Shell action scripts in real content put the
    MIMEType on the line after `<ActionScript` (PR #119 review). The element
    opens on the name alone; its body opens on the tag's own `>`."""
    repository = _bes_repository()
    assert _bes_begin("actionscript").match("<ActionScript")
    element = repository["actionscript"]
    assert [p["include"] for p in element["patterns"]] == [
        "#actionscript-other-language",
        "#actionscript-self-closing",
        "#attributes",
        "#actionscript-body",
    ]
    assert repository["actionscript-body"]["begin"] == "(>)"


def test_another_mime_type_finishes_its_start_tag_before_handing_over() -> None:
    """The rest of the tag stays a tag: attributes, then `/>` (no body) or
    `>` and a body for the XML grammar (PR #119 review)."""
    rule = _bes_repository()["actionscript-other-language"]
    assert [p["include"] for p in rule["patterns"]] == [
        "#actionscript-self-closing",
        "#attributes",
        "#actionscript-other-body",
    ]
    assert rule["end"] == r"(?=</ActionScript\s*>)|(?<=/>)"
    body = _bes_repository()["actionscript-other-body"]
    assert body["begin"] == "(>)" and body["patterns"] == [{"include": "text.xml"}]


@pytest.mark.parametrize(
    ("tag", "expected"),
    [
        ("<Relevance>", True),
        ('<Relevance Comment="x">', True),
        ('<Property Name="Version" ID="1" EvaluationPeriod="PT1H">', True),
        ('<SuccessCriteria Option="CustomRelevance">', True),
        ("<SuccessCriteria Option='CustomRelevance' >", True),
        ('<SuccessCriteria Option="OriginalRelevance">', False),
        ('<SuccessCriteria Option="RunToCompletion"/>', False),
        ("<RelevanceX>", False),
        ("<Relevance/>", False),
        ("<Properties>", False),
        ('<Relevance Comment="a > b">', True),
        ('<SuccessCriteria Comment=">" Option="CustomRelevance">', True),
        ('<SuccessCriteria Comment="Option=\'CustomRelevance\'" Option="Other">', False),
    ],
)
def test_the_relevance_bodies_are_the_ones_the_extractor_reads(tag: str, expected: bool) -> None:
    found = _bes_begin("relevance").match(tag)
    assert bool(found) is expected
    if found:
        assert found.end() == len(tag), "the tag ended inside an attribute value"


def test_the_bes_grammar_colors_only_tags_the_extractor_reads() -> None:
    text = repr(_generator().bes_grammar())
    for tag in ("Relevance", "Property", "SuccessCriteria", "ActionScript"):
        assert tag in _RELEVANT_TAGS
        assert tag in text


def test_the_bes_grammar_handles_its_elements_before_plain_xml() -> None:
    patterns = _generator().bes_grammar()["patterns"]
    assert patterns[-1] == {"include": "text.xml"}
    assert {"include": "#actionscript"} in patterns[:-1]
    assert {"include": "#relevance"} in patterns[:-1]


def test_cdata_and_entity_bodies_both_embed() -> None:
    """In or out of `<![CDATA[ ]]>`: the CDATA rule comes first, then the body
    language itself, so an entity-escaped body is embedded too."""
    repository = _bes_repository()
    for name, body in (
        ("actionscript-body", {"include": "source.bigfix-actionscript"}),
        ("relevance", {"include": "#relevance-body"}),
    ):
        rule = repository[name]
        patterns = rule["patterns"]
        assert patterns[0]["include"].startswith("#cdata"), name
        assert patterns[1] == {"include": "#entity"}, name
        assert patterns[2:] == [body], name
        cdata = repository[patterns[0]["include"].removeprefix("#")]
        assert cdata["patterns"] == [body]  # the same body, less CDATA and entities
        assert rule["contentName"].startswith("meta.embedded.block.")
        assert "contentName" not in cdata  # the element's covers it


def test_the_relevance_body_is_generated_once() -> None:
    """One repository entry that both the element and its CDATA include."""
    text = json.dumps(_generator().bes_grammar())
    assert text.count("CustomRelevance") == 2  # the start-tag lookahead's two quotings
    assert text.count("SuccessCriteria)\\\\s*>") == 2  # the string and comment guards


def test_a_relevance_string_or_comment_left_open_ends_with_its_body() -> None:
    """The relevance grammar's own rules, with the end widened to the body's."""
    relevance = _generator().relevance_grammar()["repository"]
    guards = _bes_repository()["relevance-body"]["patterns"][:-1]
    assert [guard["name"] for guard in guards] == [
        relevance["string"]["name"],
        relevance["comment"]["name"],
    ]
    for guard in guards:
        end = _python(guard["end"])
        for line in ("</Relevance>", "</Property>", "</SuccessCriteria>", "]]>"):
            found = end.search(f"open{line}")
            assert found is not None and found.start() == len("open"), (guard["name"], line)


def test_the_relevance_tags_open_and_close_from_one_list() -> None:
    """A tag added to the start rule but not to the body-end guard would let
    an unclosed string in it run into the rest of the file."""
    tags = _generator().RELEVANCE_TAGS
    begin = _bes_begin("relevance")
    guards = _bes_repository()["relevance-body"]["patterns"][:-1]
    for tag in tags:
        written = f'<{tag} Option="CustomRelevance">' if tag == "SuccessCriteria" else f"<{tag}>"
        assert begin.match(written), tag
        for guard in guards:
            found = _python(guard["end"]).search(f"open</{tag}>")
            assert found is not None and found.start() == len("open"), (tag, guard["name"])


def test_an_end_tag_closes_whatever_its_start_tag_opened() -> None:
    """The start tag's attribute conditions (`Option="CustomRelevance"`)
    cannot apply to an end tag: the end is a backreference to the name."""
    assert _bes_repository()["relevance"]["end"] == r"(</)(\2)\s*(>)"
    end = _python(_bes_repository()["actionscript"]["end"])
    assert end.match("</ActionScript>") and end.match("</ActionScript >")
    # After a self-closing `/>`, the element ends without an end tag.
    found = end.search("<ActionScript />", len("<ActionScript />"))
    assert found is not None and found.group() == ""
